# pubsender:
#    file: pubsender
#    varclass: pubsender
#    frequency: 1
cpub:
   file: socketpubsub
   varclass: cpub
   ip: 192.168.3.15
   port: 8080
   config_file: serverconfig.yaml
   frequency: 1
pubsender2:
    file: pubsender
    varclass: pubsender2
    frequency: 1
pubreceiver:
    file: pubsender
    varclass: pubreceiver
    frequency: 1
# spub:
#    file: socketpubsub
#    varclass: spub
#    frequency: 1
